namespace GameServer.Enums;

// Sourced from 1189 commondb.sdb
public enum AptitudeStat : ushort
{
    Speed = 1,
    ForwardSpeed = 2,
    JumpHeight = 3,
    DamageTaken = 4,
    DamageDealt = 5,
    Health = 6,
    MaxHealth = 7,
    Shields = 8,
    MaxShields = 9,
    AirControl = 10,
    Energy = 11,
    MaxEnergy = 12,
    EnergyRechargeDelay = 13,
    EnergyRechargeRate = 14,
    ThrustStrength = 15,
    ThrustAirControl = 16,
    Friction = 17,
    SinBonus = 18,
    SinVulnerability = 19,
    TurnRate = 20,
    FireRateModifier = 21,
    AmmoConsumption = 22,
    AccuracyModifier = 23,
    CooldownModifier = 24,
    Progress = 25,

    // 1962-era extensions (mirrors StatModifierIdentifier naming where mapped)
    HealingReceivedMult = 26,
    TurnSpeed = 27,
    ExperienceMult = 28,
    WeaponSplashRadius = 29,
    Damage = 30,
    Lifesteal = 31,
    PoisonDamage = 32,
    PiercingDamage = 33,
    IceDamage = 34,
    JetEnergy = 35,
    JetEnergyRechargeDelay = 36,
    JumpHeight2 = 37,
    CraterDamage = 38,
    CraterSplashRadius = 39,
    CraterRecharge = 40,
    AfterburnerImpulsePotency = 41,
    AfterburnerSpeedBonusDuration = 42,
    EliteRankXpBonus = 43,
    MissileBarrageDamage = 44,
    XpBonus = 45,
    Unknown_46 = 46,
    OverchargeDuration = 47,
    OverchargePotency = 48,
    OverchargeRecharge = 49,
    GravityMult = 50,
    Unknown_51 = 51,
    Unknown_52 = 52,
    Unknown_53 = 53,
    ResourceStatusBonus = 54,
    Unknown_55 = 55,
    Unknown_56 = 56,
    Unknown_57 = 57,
}